CREATE TABLE user (
    id INT(4) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(200) NOT NULL,
    email VARCHAR(100) NOT NULL,
    userlevel VARCHAR(10) NOT NULL
)  ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE announce (
	id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    information varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;